// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.33;

import {Test} from "forge-std/Test.sol";
import {AAStarBLSKeyRegistry} from "../src/validators/AAStarBLSKeyRegistry.sol";

// issue #45 Fix 1 — replay-binding test (red->green).
// A real 3-node BLS aggregate was produced off-chain (noble-curves longSignatures, the exact
// DVT stack) over messagePoint = G2.hashToCurve(userOpHash_A, {DST}). Fixture generated by
// /tmp/gen_agg.mjs. The aggregate is valid for userOpHash_A and MUST be rejected for a
// different userOpHash_B, because validate() now recomputes the message point from `hash`.
//
// REQUIRES EIP-2537 → run with `--evm-version prague`. Skipped under the repo default cancun.
contract BLSReplayBindingTest is Test {
    AAStarBLSKeyRegistry bls;

    bytes32 constant USEROPHASH_A = 0x1111111111111111111111111111111111111111111111111111111111111111;
    bytes32 constant USEROPHASH_B = 0x8bb1b199f427dfc49e5fe40f2f3278cb1a48587824b78263051c8c4d81d77a81;

    bytes32 constant NODE0 = keccak256("replay-node-0");
    bytes32 constant NODE1 = keccak256("replay-node-1");
    bytes32 constant NODE2 = keccak256("replay-node-2");

    bytes PK0 =
        hex"0000000000000000000000000000000000018a69dc077fab6cfcbccb3885ad65db01da0c02491dff25d29ce90d03bc68cb52ad49bead602238cf467eafdb48cd0000000000000000000000000000000002becaee44a5a46c7330c9c7a7212c11542851f5dd029554a40db9b14e004f0c1f1d879d9948a9a7b477f8db2641fc8d";
    bytes PK1 =
        hex"000000000000000000000000000000000bc90707abc9ce61d525419ceda6aacd8a3b4f222bf63e18d7c6ba56b5c8f9642375e1424b2e3d3ab0c7324bcfd2ecea0000000000000000000000000000000016116e6a87fc280d377d071a22b78316eca19ac05435a378e4f9b41e4d1650ce90dd139ea84feb1c13ac8f9db393e7e7";
    bytes PK2 =
        hex"000000000000000000000000000000000e53de59dcec974f6ec859282f92820ae22198ba0c0405c1ac0e0878959f6528340c4ca46d6907a92c997b90dd5b83af0000000000000000000000000000000002f3e512ee7a9a7d45e8679c1e808fb2751b53aeb254f24ba1499719e8a9289c3dd88db9d00c18edf9d0bb306fb5526d";
    bytes AGGSIG =
        hex"0000000000000000000000000000000011c5f99ff65ef3a521b5c870d6e2d7343284b8ba946f0e6b237dc057617eb6cc8736290a8724f75e90a5634d48467f2e000000000000000000000000000000001384aedc1b85ae258fbbf830941505cbd1aa2da8932cc34c1257bece2e6d35ba0a25213f71560cfff2daba5a5d7d51f0000000000000000000000000000000001782a5b74dd7e0b7dd781e99280c00724631ae6980431152777efa6deae6bd26c57f6c549ff4a2eb7c6cd5543909f7c3000000000000000000000000000000000cddb637f41155e1f8654a5e39db04c1bebc8150d9e8dc1f5fd1b75ce477b1c4dcd5b8c9da01473d8e5010cb56983737";

    function setUp() public {
        bls = new AAStarBLSKeyRegistry();
        bls.registerPublicKey(NODE0, PK0);
        bls.registerPublicKey(NODE1, PK1);
        bls.registerPublicKey(NODE2, PK2);
    }

    function _has2537() internal view returns (bool) {
        bytes memory inp = new bytes(128);
        bool ok;
        uint256 rds;
        assembly {
            ok := staticcall(gas(), 0x11, add(inp, 0x20), 128, 0, 0)
            rds := returndatasize()
        }
        return ok && rds == 256;
    }

    // New-format signature: [nodeId0][nodeId1][nodeId2][aggSig(256)]
    function _sig() internal view returns (bytes memory) {
        return abi.encodePacked(NODE0, NODE1, NODE2, AGGSIG);
    }

    function test_validAggregate_acceptedForCorrectHash() public view {
        if (!_has2537()) return;
        assertEq(bls.validate(USEROPHASH_A, _sig()), 0, "valid aggregate for A must be accepted");
    }

    function test_replay_rejectedForDifferentHash() public view {
        if (!_has2537()) return;
        // Same aggregate, different userOpHash → message point recomputed from B ≠ signed point → reject.
        assertEq(bls.validate(USEROPHASH_B, _sig()), 1, "replay onto B must be rejected");
    }

    // Demonstrates WHY the old code was vulnerable: the aggregate was signed over hashToG2(A),
    // and hashToG2(A) != hashToG2(B). The old validate() paired against a caller-supplied point
    // (always hashToG2(A) in a replay) regardless of `hash`, so submitting it for B would PASS.
    // The fix is that the point is now derived from `hash`, so A's point can never satisfy B.
    function test_signedPoint_differsFromB() public view {
        if (!_has2537()) return;
        assertTrue(
            keccak256(bls.hashToG2(USEROPHASH_A)) != keccak256(bls.hashToG2(USEROPHASH_B)),
            "hashToG2(A) must differ from hashToG2(B)"
        );
    }
}
