/**
 * Onboard Step 1: Create P-256 Passkey + KMS Wallet + Derive EOA Address
 *
 * Flow:
 *   1. Generate P-256 keypair locally (simulates WebAuthn passkey)
 *   2. Call KMS /CreateKey with P-256 public key → wallet_id + mnemonic
 *   3. Call KMS /DeriveAddress → EOA address (m/44'/60'/0'/0/0)
 *   4. Save wallet info to .env.wallet for subsequent scripts
 *
 * Usage: npx tsx scripts/onboard-1-create-keys.ts
 */

import { p256 } from "@noble/curves/p256";
import { randomBytes } from "crypto";
import { config } from "dotenv";
import { writeFileSync, existsSync } from "fs";
import { resolve } from "path";

config({ path: resolve(import.meta.dirname, "../.env.sepolia") });

const KMS_BASE_URL = process.env.KMS_BASE_URL || "https://kms.aastar.io";
const KMS_API_KEY = process.env.KMS_API_KEY;
const WALLET_ENV_PATH = resolve(import.meta.dirname, "../.env.wallet");

interface KmsResponse {
  KeyMetadata?: {
    KeyId: string;
    Description: string;
    Enabled: boolean;
  };
  Mnemonic?: string;
  Address?: string;
  PublicKey?: string;
  error?: string;
}

async function kmsRequest(
  endpoint: string,
  body: Record<string, unknown>
): Promise<KmsResponse> {
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
  };
  if (KMS_API_KEY) {
    headers["x-api-key"] = KMS_API_KEY;
  }

  const res = await fetch(`${KMS_BASE_URL}${endpoint}`, {
    method: "POST",
    headers,
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`KMS ${endpoint} failed (${res.status}): ${text}`);
  }

  return res.json();
}

// ─── Step 1: Generate P-256 Keypair ─────────────────────────────────

function generateP256Keypair() {
  const privateKey = randomBytes(32);
  const publicKey = p256.getPublicKey(privateKey, false); // uncompressed (65 bytes)

  return {
    privateKeyHex: "0x" + Buffer.from(privateKey).toString("hex"),
    publicKeyHex: "0x" + Buffer.from(publicKey).toString("hex"),
    // Extract x, y coordinates for smart contract setP256Key()
    x: "0x" + Buffer.from(publicKey.slice(1, 33)).toString("hex"),
    y: "0x" + Buffer.from(publicKey.slice(33, 65)).toString("hex"),
  };
}

async function main() {
  console.log("=== Onboard Step 1: Create Keys ===\n");

  // Step 1: Generate P-256 keypair (simulates WebAuthn passkey)
  console.log("1. Generating P-256 keypair (passkey simulation)...");
  const passkey = generateP256Keypair();
  console.log(`   Public Key: ${passkey.publicKeyHex.slice(0, 20)}...`);
  console.log(`   X: ${passkey.x.slice(0, 20)}...`);
  console.log(`   Y: ${passkey.y.slice(0, 20)}...`);

  // Step 2: Create KMS wallet with passkey public key
  console.log("\n2. Creating KMS wallet (TEE-protected)...");
  const createRes = await kmsRequest("/CreateKey", {
    Description: "airaccount-onboard-test",
    KeyUsage: "SIGN_VERIFY",
    KeySpec: "ECC_SECG_P256K1",
    Origin: "TEE_GENERATED",
    PasskeyPublicKey: passkey.publicKeyHex,
  });

  const walletId = createRes.KeyMetadata?.KeyId;
  const mnemonic = createRes.Mnemonic;
  if (!walletId) {
    throw new Error("KMS CreateKey failed: no KeyId returned");
  }
  console.log(`   Wallet ID: ${walletId}`);
  if (mnemonic) {
    console.log(`   Mnemonic: ${mnemonic.split(" ").slice(0, 3).join(" ")} ... (${mnemonic.split(" ").length} words)`);
  }

  // Step 3: Derive EOA address
  console.log("\n3. Deriving EOA address (m/44'/60'/0'/0/0)...");
  const deriveRes = await kmsRequest("/DeriveAddress", {
    KeyId: walletId,
    DerivationPath: "m/44'/60'/0'/0/0",
  });

  const eoaAddress = deriveRes.Address;
  if (!eoaAddress) {
    throw new Error("KMS DeriveAddress failed: no Address returned");
  }
  console.log(`   EOA Address: ${eoaAddress}`);

  // Step 4: Save to .env.wallet
  const walletEnv = [
    "# Generated by onboard-1-create-keys.ts",
    `# ${new Date().toISOString()}`,
    "",
    "# KMS Wallet",
    `KMS_WALLET_ID=${walletId}`,
    `KMS_EOA_ADDRESS=${eoaAddress}`,
    `KMS_DERIVATION_PATH=m/44'/60'/0'/0/0`,
    "",
    "# P-256 Passkey (for smart contract setP256Key)",
    `PASSKEY_PRIVATE_KEY=${passkey.privateKeyHex}`,
    `PASSKEY_PUBLIC_KEY=${passkey.publicKeyHex}`,
    `PASSKEY_X=${passkey.x}`,
    `PASSKEY_Y=${passkey.y}`,
    "",
    mnemonic ? `# Mnemonic (BACKUP ONLY - DO NOT SHARE)\n# MNEMONIC=${mnemonic}` : "",
    "",
  ].join("\n");

  writeFileSync(WALLET_ENV_PATH, walletEnv);
  console.log(`\n4. Saved wallet info to ${WALLET_ENV_PATH}`);

  console.log("\n=== Summary ===");
  console.log(`   KMS Wallet ID : ${walletId}`);
  console.log(`   EOA Address   : ${eoaAddress}`);
  console.log(`   Passkey X     : ${passkey.x}`);
  console.log(`   Passkey Y     : ${passkey.y}`);
  console.log("\nNext: npx tsx scripts/onboard-2-create-account.ts");
}

main().catch((err) => {
  console.error("Error:", err.message);
  process.exit(1);
});
